#!/bin/bash
#
# (c) 2025 The Phosh Developers
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Author: Guido Günther <agx@sigxcpu.org>
#
# Build and install the package

set -e

[ "$1" = "refs/heads/next" ] || exit 0

export -n GIT_DIR

cd ..
PROJECT="$(basename "$PWD")"
echo "Next branch of '$PROJECT', updating repo"

git checkout -f next
git status

DEB_BUILD_OPTIONS="nocheck"
# Generally useful to speed up build
DEB_BUILD_PROFILES="nodoc nocheck"
# Minimize phosh build
DEB_BUILD_PROFILES="$DEB_BUILD_PROFILES pkg.phosh.nolib"
# Make phoc build more useful for developement
DEB_BUILD_PROFILES="$DEB_BUILD_PROFILES pkg.phoc.embedwlroots pkg.phoc.sanitizers pkg.phoc.trace"

export DEB_BUILD_PROFILES
export DEB_BUILD_OPTIONS

dpkg-buildpackage -uc -us -rfakeroot -b

sudo debi

case $PROJECT in
  # User session services that just respawn:
  feedbackd)
    echo "Restarting $PROJECT…"
    killall "$PROJECT"
    ;;
  # Graceful restart in session
  *stevia)
    echo "Restarting user unit…"
    systemctl restart --user mobi.phosh.OSK.service
    ;;
  # Needs a session restart
  phosh|phoc)
    echo "Restarting session…"
    systemctl restart greetd
    ;;
  *)
    echo "Unknown project '$PROJECT', doing nothing"
esac
