#!/bin/bash
#
# Copyright (C) 2024 The Phosh developers
# SPDX-License-Identifier: GPL-3.0-or-later
# Author: Guido Günther <agx@sigxcpu.org>
#
# Get the issues closed in the latest release

set -e

[ -z "$1" ] || VERSION=(--since "$1")

if [ "$(dpkg-parsechangelog "${VERSION[@]}" | grep -E '(Closes|Fixes)':)" != "" ]; then
  echo "* Issues fixed:"
  dpkg-parsechangelog "${VERSION[@]}" | sed -nE 's/.*(Closes|Fixes): ((https?:|#).*)/    * \2/p'

fi
